---
title: "Lab 10"
author: "Stephanie Lee"
date: "`r Sys.Date()`"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RSQLite)
library(DBI)

# Initialize a temp in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)

dbListTables(con)
```
```{sql, connection=con}
PRAGMA table_info(actor)
```
# Exercise 1
Retrive the actor ID, first name and last name for all actors using the actor table. Sort by last name and then by first name.
```{sql connection=con}
SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name
```

# Cleanup
Run the following chunk to disconnect from the connection.
```{r cleanup}
dbDisconnect(con)
```
