---
title: "Lab 7"
author: "Stephanie Lee"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(xml2)
library(stringr)
```

## Question 1: How many sars-cov-2 papers?
Build an automatic counter of sars-cov-2 papers using PubMed. You will need to apply XPath as we did during the lecture to extract the number of results returned by PubMed in the following web address:
```{r website extraction}
# Downloading the website
website <- xml2::read_html("https://pubmed.ncbi.nlm.nih.gov/?term=sars-cov-2")

# Finding the counts
counts <- xml2::xml_find_first(website, "/html/body/main/div[9]/div[2]/div[2]/div[1]/div[1]")

# Turning it into text
counts <- as.character(counts)

# Extracting the data using regex
stringr::str_extract(counts, "[0-9,]+")
```
##Question 2: Academic publications on COVID19 and Hawaii

```{r query}
library(httr)
query_ids <- GET(
  url   = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi",
  query = list(db= "pubmed", term= "covid19 hawaii", retmax= 1000)
)
# Extracting the content of the response of GET
ids <- httr::content(query_ids) %>% 
  as.character(ids)
```


